# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title asCharTime
#' @description convert integer time values to character time strings
#'
#'
#' @param x integer vector eg: `ITime` class
#'
#' @keywords time
#' @useDynLib rcsv
#'
asCharTime <- function(x) {
    .Call('rcsv_asCharTime', PACKAGE = 'rcsv', x)
}

#' @title toTimeDay
#' @description convert character times to fraction of the day
#'
#'
#' @param x character vector, input times
#'
#' @keywords time
#' @useDynLib rcsv
#' @export
#'
toTimeDay <- function(x) {
    .Call('rcsv_toTimeDay', PACKAGE = 'rcsv', x)
}

#' @title toTimeSec
#' @description convert character times to integer seconds since midnight
#'
#'
#' @param x character vector, input times
#'
#' @keywords time
#' @useDynLib rcsv
#' @export
#'
toTimeSec <- function(x) {
    .Call('rcsv_toTimeSec', PACKAGE = 'rcsv', x)
}

